version: '3.3'

services:
  myApp:
    image: soul0silver/wwproxy:latest
    container_name: wwproxy
#    build: .
    ports:
      - 8002:8002
    environment:
      DATABASE_URL: jdbc:mysql://localhost:3309/proxy_server
      DATABASE_USERNAME: root
      DATABASE_PASS: root
      CLIENT_ID: 4c1f1010-9fd6-44d6-a740-3a9b562c77b8
      API_KEY: cac89ce6-dad0-4662-a978-633a215e8db0
      CHECKSUM_KEY: 3f3c9a8667a78814ad136bbc98b46b6eeb1a6ad503093c79720794054017843c
