spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_updates: true
        generate_statistics: true
        cache:
          use_second_level_cache: false
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://160.250.134.143:3308/test}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: ${PORT:8002}
  servlet:
    context-path: /api/v1
PAYOS_CLIENT_ID: ${CLIENT_ID:4c1f1010-9fd6-44d6-a740-3a9b562c77b8}
PAYOS_API_KEY: ${API_KEY:cac89ce6-dad0-4662-a978-633a215e8db0}
PAYOS_CHECKSUM_KEY: ${CHECKSUM_KEY:3f3c9a8667a78814ad136bbc98b46b6eeb1a6ad503093c79720794054017843c}
app:
  schedule: ${DELAY_TIME:1}
  url-list-order: https://api-app.payos.vn/organizations/738cc5a0be2011ef964c0242ac110002/statistics/payment-link
  url-login-payos: https://api-app.payos.vn/auth/sign-in
  email-payos: 0wtfwtf0@gmail.com
  pass-payos: 5036d0c586b98278a49cf30655d0013b7681020f79f8dd6a03764a72ecd397493ef1f25a188cab29e8d01315f985ab7f37d05b1f0ab9d179ecdd7caa7d8a2b7a
  x-api-key: ${X_API_KEY:bZ932tlniM}
  proxy-control-url: ${PROXY_CONTROL_URL:https://api.tsproxy.com/api/v1}
  list-path: ${LIST_PATH:/public/proxy-list}
  change-ip-path: ${CHANGE_IP_PATH:/public/reload}
  rotate-path: ${CREATE_ROTATE:/public/rotate-schedule}
  remote-port-path: ${REMOTE_PORT_PATH:/public/remote-port}
  device-ids: ${DEVICE_IDS:6794caa885efffb2841c78d6,67935a8e85efffb2848d2f51}
